---
title: "Change of Major Chronic Disease Comorbidities with Age, Gender and Developing Years"
author: 
  - "Shangzhou Wang, Shahadat Uddin"
date: "28/06/2020"
output:
  html_document:
    number_sections: true
    css: steven_style.css
bibliography: ["Disease_Trajectories_tex_1.bib", "PH_Chronic_Disease_Better.bib"]
csl: biomed-central.csl
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Generally include 3-4 paragraphs to describe the research problem, why the problem needs to be addressed etc.

As specified by the Australian Institute of Health and Welfare(AIHW), chronic diseases have a significant impact on the health sector and it is the leading cause of illness, disability and death in Australia [@aihw2016AustraliaHealth2016]. About half of Australians have at least one prominent chronic condition and nearly a quarter of all Australians had two or more chronic diseases. There are around nine out of ten deaths in 2015 closely related to chronic diseases. The prevalence of chronic diseases and the number of chronic diseases in comorbidity to the aged population group are even much higher.

Comorbidity of chronic diseases is defined as the “point-prevalent concurrence” of the diseases concerned [@schellevis1993ComorbidityChronicDiseases]. In a more general term, comorbidity is the presence of more than 1 distinct condition in an individual [@valderas2009DefiningComorbidityImplications]. Normally, there is an index condition designated and any additional condition is regarded as comorbidity. In addition to comorbidity, multimorbidity has been increasingly adopted to refer to “the co-occurrence of multiple chronic or acute diseases and medical conditions within one person”[@bayliss2008ProcessesCareDesired]. With different to the comorbidity, multimorbidity particularly means that 2 or more distinct disorders co-exist without any implicit ordering [@valderas2009DefiningComorbidityImplications]. Therefore, there isn’t an index condition designated for multimorbidity. This subtle difference could make a huge difference in terms of what kinds of research questions to be answered.

AIHW reported that for people aged over 65 years old, 87% of them have chronic conditions and 60% have comorbidities [@aihw2016AustraliaHealth2016; @aihw2018AustraliaHealth2018]. As Bayliss et al. [@bayliss2008ProcessesCareDesired] stated that there is a increasing desire for specific patient-centered care for elder multimorbidity patients. There is no doubt that comorbid and multimorbid chronic diseases are increasingly placing a greater burden on individuals, communities and health care services [@islam2014MultimorbidityComorbidityChronic]. Along with the population ageing, overall improved treatment and exposed to better medication, a substantial increasing financial burden on the health care system is foreseeable. Prevention of chronic diseases and delay progression of comorbidity have been paramount important for the quality of life and the endurability of a health care system.

Based on the recent search and as Caughey et al. stated the studies on comorbidity associated with chronic disease is relatively low [@caughey2008PrevalenceComorbidityChronic]. There is a clear need on understanding of the significant comorbidity of each chronic disease. In particular, there is no paper found with in the Australia context on the impact of age group, gender and years of development towards the comorbidity change of chronic diseases. This study aims to use the insurance claim data to explore the comorbidity of the Australia 8 most common chronic diseases. These 8 common chronic disease are [@aihw2018AustraliaHealth2018; @agdh_chronic_2019]: Arthritis, Asthma, Back pain, Cancer, Cardiovascular, Chronic obstructive pulmonary disease (COPD), Diabetes, and Mental health conditions.


# Methods

## Dataset

Data used in this study is from an Australia insurance claim data. Insurance claim data has a very long history of data collection [@mitchell1994UsingMedicareClaims]. Since insurance claim data normally covers a large patient base over a long period of time, it has widely accepted to be used for the research investigation purposes [@uddin2015AdministrativeClaimData].

In order to make use of the original data, a number of cleaning and filtering process has been applied to extract a subset of data for the research use. Particularly, only when an episode has a valid ICD code which mapped to Charlson and Elixhauser comorbidities [@quan2005CodingAlgorithmsDefining] and the further fine-tune defined chronic diseases will be used for this study. Based on these criterion, the dataset has 29,280 unique de-identified patients and the reportable year covers from 14 August 1995 to 13 April 2018. A total of 69,302 comorbidity progression instances is identified within the sub-dataset.

## Chronic Disease Code Mapping

As the study’s main focus is to explore the significance of comorbidity change for the 8 most common chronic diseases in Australia as defined by Australian Government Department of Health and Australian Institute of Health and Welfare(AIHW) [@aihw2018AustraliaHealth2018; @agdh_chronic_2019], a clear chronic disease to ICD code mapping definition needs to be determined. However, there is indeed no current clearly agreed chronic disease to ICD code mapping available in a publication, especially for the Australia context. Quan et al. [@quan2005CodingAlgorithmsDefining] bridged 30 widely adopted Elixhauser comorbidities [@elixhauser1998ComorbidityMeasuresUse; @toson2016NewICD10Version]  with ICD-9-CM and ICD-10 code. However, these comorbidity definitions are not exactly matching with the chronic diseases which public health practice normally refers to. For instance, in ICD-9-CM and ICD-10 Coding Algorithms for Elixhauser Comorbidities table, there is no back pain defined as comorbidity. Meanwhile, cardiovascular and cancer span more than one comorbidities [@quan2005CodingAlgorithmsDefining]. Therefore, directly using Elixhauser comorbidities ICD mapping to represent chronic diseases is not in line with the 8 common chronic diseases defined by by Australian Government Department of Health.

The Healthcare Cost and Utilization Project (HCUP) is a family of healthcare databases and related software tools and products developed through a USA Federal-State-Industry partnership and sponsored by the Agency for Healthcare Research and Quality (AHRQ). HCUP developed a Chronic Condition Indicator for the International Classification of Diseases based on ICD-10-CM. This database has a clear definition whether a diagnose is chronic or not. However, it is currently in a beta version and it is neither widely adopted now have a super-level chronic disease grouping to group chronic ICD code to a more common chronic disease. Nevertherless, this database provided some very useful information to determine if an ICD code is a chronic condition. In this study, this HCUP database has been used for a reference to support determine if an ICD code is chronic condition or not.

Principal Diagnosis data cube under ICD-10-AM Edition 10, 2017-18 is a database maintained by AIHW. The principal diagnosis is defined as the diagnosis established after study to be chiefly responsible for occasioning the patient’s episode of care in hospital [@PrincipalDiagnosisData]. The data cube recorded 3 to 5 ICD-10-AM diagnosis code and it is the main reference data cube used to search those 8 common chronic disease and its corresponding ICD codes. Elixhauser Comorbidities table and HCUP database are both refereed to ensure the correctness and the coverage of ICD code for a particular chronic disease. For back pain, since there is no similar definition in, the website the burden of Musculoskeletal Diseases in the Unite States is referenced to get those ICD chapter names and then use these names to seek in the Principal Diagnosis data cube.

## ICD-10-AM to ICD 9 Convertion

## Other Comorbidity



# Results

just describe the findings using a plain language


# Discussion

what are the impact of the findings, 'so-what' of the findings generally 3-4 paragraphs.


# Conclusion

Conclusion remarks and limitations of the study (1-2 paragraphs)


# Reference







